CREATE TABLE Customer (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name VARCHAR(50) NOT NULL,
  Age INTEGER NOT NULL,
  TotalPurchases DECIMAL(18, 2)
);

INSERT INTO CUSTOMER VALUES(NULL, "ABDULLAH", 27, 1000.50);
INSERT INTO CUSTOMER VALUES(NULL, "Ahmed", 50, 948.33);
INSERT INTO CUSTOMER VALUES(NULL, "Hani", 10, 5.5);
INSERT INTO CUSTOMER VALUES(NULL, "Norah", 5, 50.19);
