CREATE TABLE CUSTOMER(
  Id INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Age INT NOT NULL,
  TotalPurchases DECIMAL(18, 2),
  PRIMARY KEY (Id)
);

INSERT INTO CUSTOMER VALUES(1, "ABDULLAH", 27, 1000.50);
INSERT INTO CUSTOMER VALUES(2, "Ahmed", 50, 948.33);
INSERT INTO CUSTOMER VALUES(3, "Hani", 10, 5.0);
